"use client";

import { CalendarDays, ChevronDown, ChevronRight, CreditCard, Mail, PackagePlus, Phone, Plus, Search, ShoppingCart, Truck, X } from "lucide-react";
import { useSearchParams } from "next/navigation";
import { FormEvent, useMemo, useState } from "react";
import { demoOrders, demoSuppliers, type PurchaseItem, type PurchaseOrder, type Supplier } from "@/lib/purchasing-data";
import { money } from "@/lib/utils";

const input = "focus-ring h-11 w-full rounded-xl border border-black/10 bg-white px-3 text-sm";
const total = (order: PurchaseOrder) => order.items.reduce((sum, item) => sum + item.quantity * item.unitPrice, 0);
const paid = (order: PurchaseOrder) => order.payments.reduce((sum, payment) => sum + payment.amount, 0);

function Modal({ open, title, onClose, children, wide = false }: { open: boolean; title: string; onClose: () => void; children: React.ReactNode; wide?: boolean }) {
  if (!open) return null;
  return <div className="fixed inset-0 z-[90] overflow-y-auto bg-black/40 p-4 backdrop-blur-sm" onMouseDown={onClose}><section className={`mx-auto my-[5vh] rounded-2xl bg-white shadow-2xl ${wide ? "max-w-3xl" : "max-w-xl"}`} onMouseDown={e => e.stopPropagation()} role="dialog" aria-modal="true"><header className="flex items-center justify-between border-b border-black/[.06] p-5"><h2 className="font-display text-xl font-bold">{title}</h2><button onClick={onClose} aria-label="Cerrar"><X /></button></header>{children}</section></div>;
}

export function SuppliersPage() {
  const params = useSearchParams(); const [rows, setRows] = useState(demoSuppliers); const [query, setQuery] = useState(""); const [open, setOpen] = useState(params.get("nuevo") === "1");
  const filtered = rows.filter(s => [s.name, s.taxId, s.contact].join(" ").toLowerCase().includes(query.toLowerCase()));
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const supplier: Supplier = { id: crypto.randomUUID(), name: String(data.get("name")), taxId: String(data.get("taxId")), contact: String(data.get("contact")), phone: String(data.get("phone")), email: String(data.get("email")), address: String(data.get("address")), terms: String(data.get("terms")) }; setRows(r => [supplier, ...r]); setOpen(false); }
  return <div className="mx-auto max-w-[1400px] space-y-6"><header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-bold text-brand-700">Compras</p><h1 className="font-display text-3xl font-bold">Proveedores</h1><p className="text-sm text-black/45">Datos comerciales y contacto de cada proveedor.</p></div><button className="btn-primary" onClick={() => setOpen(true)}><Plus size={18} />Nuevo proveedor</button></header>
    <section className="card overflow-hidden"><div className="border-b border-black/[.06] p-4"><label className="flex h-11 max-w-sm items-center gap-2 rounded-xl border border-black/10 px-3"><Search size={17} className="text-black/35" /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Nombre, CUIT o contacto..." className="min-w-0 flex-1 bg-transparent text-sm outline-none" /></label></div><div className="divide-y divide-black/[.05]">{filtered.map(s => { const orders = demoOrders.filter(o => o.supplierId === s.id); const debt = orders.reduce((sum, o) => sum + total(o) - paid(o), 0); return <article key={s.id} className="grid gap-4 p-5 sm:grid-cols-[2fr_1.4fr_1fr_auto] sm:items-center"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-xl bg-brand-50 text-brand-700"><Truck size={21} /></span><div><b>{s.name}</b><p className="text-xs text-black/45">CUIT {s.taxId} · {s.terms}</p></div></div><div><p className="text-sm font-semibold">{s.contact}</p><p className="mt-1 flex gap-3 text-xs text-black/45"><span className="flex items-center gap-1"><Phone size={12} />{s.phone}</span><span className="hidden items-center gap-1 lg:flex"><Mail size={12} />{s.email}</span></p></div><div><small className="block text-black/40">Saldo pendiente</small><b className={debt ? "text-red-600" : "text-brand-700"}>{debt ? money.format(debt) : "Al día"}</b></div><ChevronRight className="hidden text-black/25 sm:block" size={18} /></article>; })}</div></section>
    <Modal open={open} title="Nuevo proveedor" onClose={() => setOpen(false)}><form onSubmit={submit} className="grid gap-4 p-5 sm:grid-cols-2"><label className="sm:col-span-2"><b className="mb-1 block text-xs">Razón social *</b><input name="name" className={input} required autoFocus /></label><label><b className="mb-1 block text-xs">CUIT *</b><input name="taxId" className={input} required /></label><label><b className="mb-1 block text-xs">Contacto</b><input name="contact" className={input} /></label><label><b className="mb-1 block text-xs">Teléfono</b><input name="phone" className={input} /></label><label><b className="mb-1 block text-xs">Email</b><input name="email" type="email" className={input} /></label><label className="sm:col-span-2"><b className="mb-1 block text-xs">Dirección</b><input name="address" className={input} /></label><label className="sm:col-span-2"><b className="mb-1 block text-xs">Condición de pago</b><input name="terms" className={input} placeholder="Ej. Cuenta corriente 30 días" /></label><div className="flex justify-end gap-2 sm:col-span-2"><button type="button" className="btn-secondary" onClick={() => setOpen(false)}>Cancelar</button><button className="btn-primary">Guardar proveedor</button></div></form></Modal>
  </div>;
}

export function PurchasesPage() {
  const params = useSearchParams(); const [orders, setOrders] = useState(demoOrders); const [open, setOpen] = useState(params.get("nuevo") === "1"); const [expanded, setExpanded] = useState<string | null>("p1"); const [paymentOrder, setPaymentOrder] = useState<string | null>(null); const [items, setItems] = useState<PurchaseItem[]>([{ description: "", quantity: 1, unitPrice: 0 }]);
  const sorted = useMemo(() => [...orders].sort((a,b) => b.date.localeCompare(a.date)), [orders]);
  function createOrder(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const order: PurchaseOrder = { id: crypto.randomUUID(), number: `PED-${String(125 + orders.length).padStart(5,"0")}`, date: String(data.get("date")), supplierId: String(data.get("supplier")), status: "Pendiente", items: items.filter(i => i.description && i.quantity > 0), payments: [] }; if (!order.items.length) return; setOrders(r => [order, ...r]); setItems([{ description: "", quantity: 1, unitPrice: 0 }]); setOpen(false); setExpanded(order.id); }
  function addPayment(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); setOrders(rows => rows.map(order => { if (order.id !== paymentOrder) return order; const payments = [...order.payments, { id: crypto.randomUUID(), date: String(data.get("date")), amount: Number(data.get("amount")), method: String(data.get("method")) }]; const nextPaid = payments.reduce((s,p) => s + p.amount, 0); return { ...order, payments, status: nextPaid >= total(order) ? "Pagado" : "Parcial" }; })); setPaymentOrder(null); }
  return <div className="mx-auto max-w-[1400px] space-y-6"><header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-bold text-brand-700">Abastecimiento</p><h1 className="font-display text-3xl font-bold">Pedidos a proveedores</h1><p className="text-sm text-black/45">Compras, artículos pedidos y pagos ordenados por fecha.</p></div><button className="btn-primary" onClick={() => setOpen(true)}><Plus size={18} />Nuevo pedido</button></header>
    <section className="grid gap-4 sm:grid-cols-3">{[["Total comprado", orders.reduce((s,o) => s + total(o),0), ShoppingCart],["Total pagado",orders.reduce((s,o) => s + paid(o),0),CreditCard],["Pendiente",orders.reduce((s,o) => s + total(o)-paid(o),0),CalendarDays]].map(([label,value,Icon]) => { const I = Icon as typeof ShoppingCart; return <article className="card p-5" key={String(label)}><I size={20} className="text-brand-600" /><p className="mt-3 text-sm font-semibold text-black/45">{String(label)}</p><b className="font-display text-2xl">{money.format(Number(value))}</b></article>; })}</section>
    <section className="card overflow-hidden"><div className="divide-y divide-black/[.06]">{sorted.map(order => { const supplier = demoSuppliers.find(s => s.id === order.supplierId); const orderTotal = total(order); const orderPaid = paid(order); const isOpen = expanded === order.id; return <article key={order.id}><button onClick={() => setExpanded(isOpen ? null : order.id)} className="grid w-full gap-3 p-5 text-left sm:grid-cols-[1fr_1.4fr_1fr_1fr_1fr_auto] sm:items-center"><div><b>{order.number}</b><p className="text-xs text-black/45">{new Date(`${order.date}T12:00:00`).toLocaleDateString("es-AR")}</p></div><b className="text-sm">{supplier?.name}</b><div><small className="block text-black/40">Total</small><b>{money.format(orderTotal)}</b></div><div><small className="block text-black/40">Pagado</small><b className="text-brand-700">{money.format(orderPaid)}</b></div><span className={`w-fit rounded-full px-2.5 py-1 text-xs font-bold ${order.status === "Pagado" ? "bg-brand-50 text-brand-700" : order.status === "Parcial" ? "bg-amber-50 text-amber-700" : "bg-red-50 text-red-700"}`}>{order.status}</span><ChevronDown size={18} className={`transition ${isOpen ? "rotate-180" : ""}`} /></button>{isOpen && <div className="bg-canvas/60 px-5 pb-5"><div className="grid gap-5 pt-5 lg:grid-cols-2"><div><h3 className="text-sm font-bold">Artículos pedidos</h3><div className="mt-2 overflow-hidden rounded-xl border border-black/[.07] bg-white">{order.items.map(item => <div key={item.description} className="grid grid-cols-[1fr_auto] gap-3 border-b border-black/[.05] p-3 last:border-0"><span className="text-sm">{item.quantity} × {item.description}</span><b className="text-sm">{money.format(item.quantity*item.unitPrice)}</b></div>)}</div></div><div><div className="flex items-center justify-between"><h3 className="text-sm font-bold">Pagos realizados</h3>{orderPaid < orderTotal && <button onClick={() => setPaymentOrder(order.id)} className="text-xs font-bold text-brand-700">+ Registrar pago</button>}</div><div className="mt-2 overflow-hidden rounded-xl border border-black/[.07] bg-white">{order.payments.length ? order.payments.map(p => <div key={p.id} className="flex justify-between border-b border-black/[.05] p-3 text-sm last:border-0"><span>{new Date(`${p.date}T12:00:00`).toLocaleDateString("es-AR")} · {p.method}</span><b>{money.format(p.amount)}</b></div>) : <p className="p-4 text-sm text-black/40">Todavía no se registraron pagos.</p>}<div className="flex justify-between bg-red-50 p-3 text-sm text-red-700"><b>Saldo pendiente</b><b>{money.format(orderTotal-orderPaid)}</b></div></div></div></div></div>}</article>; })}</div></section>
    <Modal open={open} title="Nuevo pedido" onClose={() => setOpen(false)} wide><form onSubmit={createOrder} className="space-y-5 p-5"><div className="grid gap-4 sm:grid-cols-2"><label><b className="mb-1 block text-xs">Proveedor *</b><select name="supplier" className={input}>{demoSuppliers.map(s => <option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label><b className="mb-1 block text-xs">Fecha de compra *</b><input name="date" type="date" required defaultValue={new Date().toISOString().slice(0,10)} className={input} /></label></div><div><div className="mb-2 flex justify-between"><b className="text-sm">Artículos del pedido</b><button type="button" className="text-xs font-bold text-brand-700" onClick={() => setItems(r => [...r,{description:"",quantity:1,unitPrice:0}])}>+ Agregar artículo</button></div>{items.map((item,index) => <div className="mb-2 grid grid-cols-[1fr_75px_120px_auto] gap-2" key={index}><input required value={item.description} onChange={e => setItems(r => r.map((x,i) => i === index ? {...x,description:e.target.value}:x))} placeholder="Descripción" className={input} /><input type="number" min="1" value={item.quantity} onChange={e => setItems(r => r.map((x,i) => i === index ? {...x,quantity:Number(e.target.value)}:x))} className={input} /><input type="number" min="0" value={item.unitPrice} onChange={e => setItems(r => r.map((x,i) => i === index ? {...x,unitPrice:Number(e.target.value)}:x))} className={input} /><button type="button" onClick={() => setItems(r => r.filter((_,i) => i !== index))} aria-label="Quitar" className="text-red-500"><X size={17} /></button></div>)}</div><div className="flex items-center justify-between border-t border-black/[.06] pt-4"><b>Total: {money.format(items.reduce((s,i) => s+i.quantity*i.unitPrice,0))}</b><div className="flex gap-2"><button type="button" className="btn-secondary" onClick={() => setOpen(false)}>Cancelar</button><button className="btn-primary"><PackagePlus size={17} />Crear pedido</button></div></div></form></Modal>
    <Modal open={Boolean(paymentOrder)} title="Registrar pago" onClose={() => setPaymentOrder(null)}><form onSubmit={addPayment} className="grid gap-4 p-5 sm:grid-cols-2"><label><b className="mb-1 block text-xs">Fecha *</b><input name="date" type="date" required defaultValue={new Date().toISOString().slice(0,10)} className={input} /></label><label><b className="mb-1 block text-xs">Importe *</b><input name="amount" type="number" min="1" required className={input} /></label><label className="sm:col-span-2"><b className="mb-1 block text-xs">Forma de pago</b><select name="method" className={input}><option>Transferencia</option><option>Efectivo</option><option>Cheque</option><option>Tarjeta</option></select></label><div className="flex justify-end gap-2 sm:col-span-2"><button type="button" className="btn-secondary" onClick={() => setPaymentOrder(null)}>Cancelar</button><button className="btn-primary">Guardar pago</button></div></form></Modal>
  </div>;
}
