import { ArrowLeft, Calendar, Gauge, ShieldCheck, UserRound, Wrench } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";
import { vehicles } from "@/lib/demo-data";

export default async function VehicleDetail({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const vehicle = vehicles.find(v => v.id === id); if (!vehicle) notFound();
  return <div className="mx-auto max-w-6xl space-y-6"><Link href="/vehiculos" className="inline-flex items-center gap-2 text-sm font-bold text-black/50 hover:text-ink"><ArrowLeft size={16} />Volver a vehículos</Link>
    <section className="overflow-hidden rounded-3xl bg-[#10251e] p-6 text-white shadow-card sm:p-8"><div className="flex flex-col gap-6 sm:flex-row sm:items-end"><div className="grid size-20 place-items-center rounded-2xl bg-white/10"><span className="h-8 w-14 rounded-lg border-2 border-white/70" /></div><div className="flex-1"><p className="text-sm font-bold text-brand-500">{vehicle.brand} {vehicle.model}</p><h1 className="font-display text-4xl font-bold tracking-wider">{vehicle.plate}</h1><p className="mt-1 text-sm text-white/50">{vehicle.year} · {vehicle.color}</p></div><button className="btn-primary"><Wrench size={17} />Nueva orden</button></div></section>
    <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[[Gauge, "Kilometraje", `${vehicle.mileage.toLocaleString("es-AR")} km`], [UserRound, "Propietario", vehicle.customer], [Calendar, "Última visita", vehicle.lastService], [ShieldCheck, "Estado", vehicle.status]].map(([Icon, label, value]) => { const I = Icon as typeof Gauge; return <article className="card p-5" key={String(label)}><I size={20} className="text-brand-600" /><small className="mt-4 block text-black/40">{String(label)}</small><b>{String(value)}</b></article>; })}</section>
    <section className="card p-6"><h2 className="font-display text-xl font-bold">Historial del vehículo</h2><div className="mt-6 border-l-2 border-brand-100 pl-6"><div className="relative pb-8"><span className="absolute -left-[31px] top-0 grid size-4 place-items-center rounded-full bg-brand-500 ring-4 ring-white" /><p className="text-xs font-bold uppercase tracking-wider text-brand-700">{vehicle.lastService}</p><h3 className="mt-1 font-bold">Ingreso al taller</h3><p className="text-sm text-black/45">Kilometraje registrado: {vehicle.mileage.toLocaleString("es-AR")} km</p></div><div className="relative"><span className="absolute -left-[31px] top-0 size-4 rounded-full bg-black/20 ring-4 ring-white" /><p className="text-xs font-bold uppercase tracking-wider text-black/40">Visita anterior</p><h3 className="mt-1 font-bold">Service programado</h3><p className="text-sm text-black/45">Aceite, filtros y chequeo general.</p></div></div></section>
  </div>;
}
